### ISSUE TITLE
denormalize normalized

### ISSUE THREAD

**Issue by olosegres** [yury-dymov/json-api-normalizer#14]
Hi Yury

How do you send data in body of POST, PUT, PATCH requests to API methods?
Is it possible to convert simplified result of `build` function from 'redux-object' lib to json, specified with JSON API standard?

**Comment by yury-dymov** [comment]
Hi @olosegres,

I guess there is no general solution for this task. `redux-object` builds an object from your store. However, API might require not a full object but certain fields depend on the business logic. Especially, then you are dealing with objects with complicated structure and relationships. For example, if you create a post with a couple of images, how would library guess, what should be sent? Are there one API call or several? This would vary from backend to backend.
