### ISSUE TITLE
Arrays in attributes get converted to objects

### ISSUE THREAD

**Issue by papermana** [yury-dymov/json-api-normalizer#22]
Since the change in 0.4.3, arrays in attributes get converted to objects when normalizing. I.e. if I have data which looks like this
```
...
attributes: {
  someArray: ['foo', 'bar'],
...
```
it will now get normalized into
```
...
attributes: {
  someArray: {
    '0': 'foo',
    '1': 'bar',
  },
...
```

I don't suppose this is intentional. (?) It's also breaking. (I know I can avoid it using the `camelizeKeys` flag but a patch release shouldn't make me do any changes to my code.)

**Comment by rouwe111** [comment]
I have the same problem. Can't update to the latest version because I will have to rewrite a lot of code where I use `.map()`

**Comment by yury-dymov** [comment]
Yeah, this is a bug. Will fix this within next 2-3 hours.
