### ISSUE TITLE
Attributes of type Date are converted to empty objects after normalizing.

### ISSUE THREAD

**Issue by flsilva** [yury-dymov/json-api-normalizer#23]
After upgrading to 0.4.3 (or 0.4.4) a normalized attribute containing a Date value returns an empty object. It works on 0.4.2.

The following is a simplified version of what I have running:

```
const obj = {
  data: {
    id: '1',
    type: 'projects',
    attributes: {
      'started-at': new Date(),
    },
  },
};
console.log(normalize(obj)); // startedAt is now an empty object {} instead of a Date object
```

Great library by the way!

**Comment by yury-dymov** [comment]
Please welcome 0.4.5.
Thank you for a good catch
