### ISSUE TITLE
Ordered collections

### ISSUE THREAD

**Issue by rupurt** [yury-dymov/json-api-normalizer#24]
Hi,

Do you have a recommendation on how to handle an ordered collection of JSON API data? `Normalizr` returns an [array of id's](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#arraydefinition-schemaattribute) as the result property

e.g.

```js
{
  "data": [
    {
      "type": "category",
      "id": "abc123",
      "attributes": {
        "name": "Category 1"
       }
    },
    {
      "type": "category",
      "id": "abc456",
      "attributes": {
        "name": "Category 2"
      }
    }
  ]
}
```

Returns

```js
{
  categories: {
    "abc123": {
      "id": "abc123",
      "attributes": {
        "name": "Category 1"
      }
    },
    "abc456": {
      "id": "abc456",
      "attributes": {
        "name": "Category 2"
      }
    }
  }
}
```

**Comment by yury-dymov** [comment]
Along with data `json-api-normalizer` returns `meta` object, which preserves the shape of backend response.

**Comment by rupurt** [comment]
@yury-dymov sweet.

Just a heads up in case anyone else comes across this, you need to provide the `endpoint` option on the call to `normalize`.

```js
normalize(json, { endpoint: "/categories" })
```
