### ISSUE TITLE
Meta keys not camelCased

### ISSUE THREAD

**Issue by InputOutput** [yury-dymov/json-api-normalizer#27]
Hi, we're working with JSON-API documents with keys that are lower snake cased but have code standards for lower camel case in the actual code. The camelcase option works fine for the attribute keys but does not seem to convert the meta keys correctly. Is this by design or is it a bug?

best regards,

Jelte Werkhoven
Kaartje2go.nl

**Comment by yury-dymov** [comment]
Sounds like a bug to me. PR is welcome or you can wait untill the end of the week, and I will fix it myself.

**Comment by InputOutput** [comment]
I'm sorry I did not get round to fixing it myself. Might do it next week unless you get there first ;)
