### ISSUE TITLE
Server side sort order is lost after calling normalize()

### ISSUE THREAD

**Issue by pcs2112** [yury-dymov/json-api-normalizer#28]
The first log is the data received from the server, the second log is the data after calling normalize()
Initial server order is ID 6, 1, 2, 3
After normalize() is called the  order is ID 1,2,3,6

<img width="940" alt="screen shot 2017-12-13 at 9 13 07 pm" src="https://user-images.githubusercontent.com/600095/33972176-89870fbc-e04a-11e7-9ded-cbc1df6067a1.png">

**Comment by yury-dymov** [comment]
Yeah, this is a side effect of having maps instead of arrays after normalization. If order is important, you may restore it from `meta` attribute (please read docs for more info)

**Comment by pcs2112** [comment]
@yury-dymov Really appreciate you getting back to me so fast. I'll look into meta to restore the ordering

**Comment by jayarjo** [comment]
@pcs2112 did you find a solution to this problem?
