### ISSUE TITLE
Serializing for POST requests

### ISSUE THREAD

**Issue by jwtong** [yury-dymov/json-api-normalizer#30]
My endpoint receives data in JSON:API format, so I need some way to take the normalized data in my state and serialize/parse it back into JSON:API before I make a POST request. Are you aware of anyway to do this easily? Thanks!

**Comment by yury-dymov** [comment]
I personally haven't dealt with such problem, so I can't really suggest any particular solution. 

However, you may search for any good library, which supports JSON:API serialization, which is the opposite operation of what my library does. Should be pretty straightforward.
