### ISSUE TITLE
Why does the type gets omitted?

### ISSUE THREAD

**Issue by orangecoloured** [yury-dymov/json-api-normalizer#32]
Not sure why the type is not being converted along with the rest of the properties.
The problem is that I can't get the type from within the entity.

For example I have a collection of polymorphic relationships `drinks`. And it can be `coffee`, `tea`, `milk`, etc. Processing a single `drink` as it is I don't know its type, because the current implementation assumes that I already know the type either from the relationship or from elsewhere.

So the input would look like this:
```
{
  "drinks": [
    {
      "id": "1",
      "type": "coffee"
    },
    {
      "id": "5",
      "type": "tea"
    },
    {
      "id": "4",
      "type": "milk"
    }
  ]
}
```

And here's the desired output:
```
"coffee": {
  "1": {
    "id": "1",
    "type": "coffee"
  },
},
"milk": {
  "4": {
    "id": "4",
    "type": "milk"
  },
},
"tea": {
  "5": {
    "id": "5",
    "type": "tea"
  }
}
```

**Comment by yury-dymov** [comment]
We may add `type` of course, but seems I don't understand the issue as you already have your type on the top level. Basically, everything under `tea` section has type `tea`. Maybe I need to learn more about your use-case.

**Comment by orangecoloured** [comment]
I need to be able to process the entity without the context. So having a `tea` body sent to some `processDrink` function, it should be able to identify the type of the entity and do stuff accordingly. If the type is `tea` we can add sugar, if it's `milk` we can warm it up, etc.

Otherwise I have to explicitly specify the type every time I pass the `drink` entity to that function. And it's a bit fussy because I need to pass the type from the very relationship.

**Comment by yury-dymov** [comment]
Ok, I see. You may fire a PR or wait until the end of the week when I'll have some time to do it myself.

**Comment by yury-dymov** [comment]
Thank you. Published update to npm

**Comment by a-komarev** [comment]
Thank you for a such quick response!

**Comment by yury-dymov** [comment]
:) I will also need to update documentation but I'll do this on weekends
