### ISSUE TITLE
Configurable camelizing type values

### ISSUE THREAD

**Issue by a-komarev** [yury-dymov/json-api-normalizer#34]
As was discovered in PR https://github.com/yury-dymov/json-api-normalizer/pull/33 there is potential issue with camelizing type's values inside relationships data objects.

Despite camelizing option explicitly called: `camelizeKeys: true` it's affecting type values too.
It will be great to have separate configurable option to camelize type values.

Input:
```js
const json = {
  data: [
    {
      type: 'post',
      relationships: {
        'rel1-to-camelize': {
          data: [
            {
              id: 4,
              type: 'type1-to-camelize',
            },
          ],
        },
      },
      id: 2620,
    },
  ],
};
```

Output:
```js
const output = {
  post: {
    2620: {
      type: 'post',
      id: 2620,
      relationships: {
        rel1ToCamelize: {
          data: [
            {
              id: 4,
              type: 'type1ToCamelize',
            },
          ],
        },
      },
    },
  },
};
```

In my point of view this should work by this way:
```js
result = normalize(json, {
    camelizeKeys: true,
    camelizeTypeValues: true,
});
```

And `camelizeTypeValues` should be in `false` state by default.

**This is breaking change**

**Comment by a-komarev** [comment]
After this implementation top-level `type` value should be affected by this option too.

**Comment by yury-dymov** [comment]
I don't mind but I would prefer that by defaul: `camelizeTypeValues = camelizeKeys`

**Comment by a-komarev** [comment]
I just don't see any case where you need to mutate values. It's clearly understood why it could be required for keys (for easier properties access), but for values it's not so obvious behavior. But maybe it's only for me.
Anyway if this will be configurable - it will be not a big problem. I think it's more matter of taste.

**Comment by yury-dymov** [comment]
The thing is that I don't need this feature but I understand that others might need it.

I agree that mutating value is a weird behavior in a vacuum but maybe, just maybe some folks want to be consistent here and there.

**Comment by a-komarev** [comment]
I agree that consistency is important. And additionally there could be case when you need to search through the resources stored in your local repository by their type key. And since they are camelized this will be easier then.

**Comment by yury-dymov** [comment]
Thank you for the help :)
