### ISSUE TITLE
data:null in relationships produces error TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by AndreyMirzoyan** [yury-dymov/json-api-normalizer#4]
Normalization proudces error "TypeError: Cannot read property 'id' of null" in this example

`...
        {
            "attributes": {
                "action": "ping",
            },
            "id": "14",
            "relationships": {
                "ad_network": {
                    "data": null
                }
            },
            "type": "app_actions"
        }
...`

To fix this error, please replace 
`if (typeof object[key].data !== 'undefined')`
with 
`if (typeof object[key].data !== 'undefined' && object[key].data !== null) {`

**Comment by yury-dymov** [comment]
Hi @AndreyMirzoyan,

thank you for your feedback, please check the new version.

Kind regards,
Yury.

**Comment by AndreyMirzoyan** [comment]
Thanks! It sloves my problem
