### ISSUE TITLE
Server side sort order is lost after calling normalize()

### ISSUE THREAD

**Issue by aliceathens** [yury-dymov/json-api-normalizer#40]
I looked at your previous closed issue #28

I am having the exact same issue however not sure what you mean by 'Metadata' could you please help with further explanation? 

I need to keep the server response order when calling normalise.

Thanks!

**Comment by yury-dymov** [comment]
You may find this in readme and in more detail here: https://www.smashingmagazine.com/2017/05/json-api-normalizer-redux/

**Comment by emp823** [comment]
Just to add more detail, you could store the ids (in their original order) in the meta object.

ex. `meta: { ids: [2, 5, 4, 1] }`

Could do this just before normalizing or on the server.

**Comment by jayarjo** [comment]
@emp823 doesn't seem to have any effect in my case. Has anything changed?
