### ISSUE TITLE
denormalization for post to API

### ISSUE THREAD

**Issue by mrichar1** [yury-dymov/json-api-normalizer#42]
Hi,

Just started experimenting with this project and Vue/Vuex, and it's a great way to normalize jsonapi data for storing state.

I was wondering if there were any plans to also add a 'reverse' denormalization method that reconstructs jsonapi from the normalized data?

**Comment by yury-dymov** [comment]
Hi,

You may have a look at my repo redux-object, which builds objects from normalized  store. While it might not suit your needs perfectly, the source code might give some ideas

**Comment by benlieb** [comment]
Also interested in this.

**Comment by mrichar1** [comment]
@benlieb If it's useful I ended up implementing an alternative module specifically for jsonapi with  Vue/Vuex: 

https://github.com/mrichar1/jsonapi-vuex

**Comment by benlieb** [comment]
@mrichar1 I glanced over your library and it's not obvious how to turn the data back into JSONAPI format to post back to the server for updates. Did I miss it? That's what this discussion is about.

**Comment by mrichar1** [comment]
The library abstracts API access away entirely, so you only need to 'operate' using the normalised form. a GET to the API returns normalised data, and a POST or PATCH expects normalised data, converting it before sending it onwards.

Saying that, the `utils` module exposes the `normToJsonapi`that is used internally if it's needed to be used directly.

If you have any other questions, feel free to open an issue on the project to avoid going too far off-topic in this issue.

**Comment by benlieb** [comment]
@mrichar1 interesting I'll take a closer look. Is it only for Vue?
