### ISSUE TITLE
[Feature Request] Preserve the order of an array after normalizing

### ISSUE THREAD

**Issue by SebastiaanNijland** [yury-dymov/json-api-normalizer#43]
Our API returns an array of objects in a certain order. The normalizer converts that array into an object, but this object is sorted by the id of all the objects in the original array. This is not the order in which the API returned them.

The issue is a JavaScript specific one, solved by the [Map Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). I'm not sure which part of the normalizer causes the sorting.

**Comment by yury-dymov** [comment]
Please refer to https://github.com/yury-dymov/json-api-normalizer/issues/24, https://github.com/yury-dymov/json-api-normalizer/issues/28, https://github.com/yury-dymov/json-api-normalizer/issues/37, https://github.com/yury-dymov/json-api-normalizer/issues/40

**Comment by SebastiaanNijland** [comment]
The thing is that this is a specific JSON api feature: http://jsonapi.org/format/#fetching-sorting

It feels counter-intuitive that we need to provide an extra object with the sorting in the `meta` fields, because the sorting was already done by the API. I understand that a Map is not always a good solution, but I feel that it actually solves the problem for a lot of other cases.

**Comment by yury-dymov** [comment]
Absolutely, however this will fix only small thing: preserving sorting order after normalization. Once the data is in the store, you would have to fetch it from there and you'll face the same issue again. Unless you are storing it as an array, which has some other trade-offs...
