### ISSUE TITLE
Селекторы для вычисляемого endpoint-а

### ISSUE THREAD

**Issue by winlx** [yury-dymov/json-api-normalizer#45]
Добрый день!
Подскажите, как делать выборку данных по endpoint, если он вычисляется внутри компоненты.
Пример:
Есть таблица товаров, при переходе на товар открывается url следующего вида /products/524, где 524 это id товара. То есть вручную указать endpoint в компоненте товара в mapStateToProps  state.data.meta['/products/524'] я не могу, так как endpoint с id заранее не знаю, он будет зависеть от выбора товара в таблице.

**Comment by yury-dymov** [comment]
Привет,

1) Вариант 1: если ты отрендерил таблицу, то данные у тебя уже должны быть и ты их просто передаешь другому компоненту
2) Вариант 2: у тебя нет всех данных и нужно сделать запрос, чтобы получить что-то еще. В этом случае у тебя будет id и тип (ItemDetail, например). Твоя страница будет через connect иметь доступ к store, соответственно по id и типу ты сможешь вытащить все необходимое и отразить.

Если оба варианта тебе не подходят, то скорее всего есть какие-то концептуальные проблемы с архитектурой, и это не является проблемой этой библиотеки

**Comment by winlx** [comment]
Спасибо за ответ. Есть еще вопросы.
По варианту 1: для таблицы данные загружаются с минимумом полей, а для загрузке всех полей сущности используется отдельный запрос.
По варианту 2: при таком варианте я могу получить нужные данные, но в таком случае у меня нет доступа к метаданным запроса, например к loading для спинера загрузки.

Получается, если мне нужно получить метаданные, то нужно запрос сделать в одной компоненте, потом в дочернюю компоненту отдать endpoint в props для селектора, в котором можно сделать так:
`
function mapStateToProps(state, props) {
    const loading = state.data.meta[props.endpoint].loading;

    return { loading };
}
`
Я только к такому пришел, может я что-то упускаю и есть вариант чтобы не делать две компоненты (в одной запрос, а в дочерней получаем данные из meta)?

**Comment by yury-dymov** [comment]
Выглядит вполне ок. Если loading = true -> показываем стандартный элемент UI с каким-нибудь спиннером. Как данные пришли — их и отображаем. 

Единственное, компоненты сами запросы не делают, они лишь вызывают экшены через редуксовский dispatch и те, если необходимо, уже лезут в бэкенд, зная и про endpoint и все остальное — им только id надо передать.

**Comment by winlx** [comment]
Спасибо за ответы. Придумаю какой-нибудь HOC для этих манипуляций.
