### ISSUE TITLE
Bundle size because of lodash.merge

### ISSUE THREAD

**Issue by casertap** [yury-dymov/json-api-normalizer#49]
I added just lodash.merge to my packages
```
    "lodash.merge": "^4.6.1",
```
So I can follow your redux example and do:
```
export function jsonapi(state = initialState, action) {
  switch (action.type) {
    case API_DATA_SUCCESS:
      return {
        ...merge(
          {},
          state,
          merge({}, action.response, {
            meta: {[action.endpoint]: {loading: false}},
          })
        ),
      };
    case API_DATA_REQUEST:
      return {
        ...merge({}, state, {meta: {[action.endpoint]: {loading: true}}}),
      };
    default:
      return state;
  }
}
```

![screenshot from 2018-09-24 11-47-35](https://user-images.githubusercontent.com/284394/45935580-28101900-bff0-11e8-84bf-2a2570ccda9d.png)

`lodash` and `lodash.merge` are huge in my bundle.
Is there any easy way I can achieve the merge easily without lodash?

**Comment by casertap** [comment]
Actually, this has nothing to do with my code using `lodash.merge` it is because `json-api-normalizer` is itself including lodash. Is there a way around that? 
I think `lodash` is really too big.

**Comment by yury-dymov** [comment]
You may have a look here: https://github.com/yury-dymov/json-api-normalizer/blob/master/src/normalize.js

I am including only small portion of lodash, which should add only imported functions and not the whole library. You may fork the repo and replace lodash usage with your custom shallow implementations, which might break in older browsers but make your bundle a bit smaller.
