### ISSUE TITLE
Fix for camelizeKeys not backwards compatible

### ISSUE THREAD

**Issue by hartzis** [yury-dymov/json-api-normalizer#50]
Hey, wanted to just inform you about an issue we have upgrading `json-api-normalizer`.

We used `camelizeKeys` option but had to work with the "broken" nature of it not camelizing links, so we had to reference the dashed notation `item-one`. When we upgraded from `0.4.8` to `0.4.14` it broke our app/tests as it now camelizing "correctly".

Just a future note i'd like to argue that even though the patches "fixed" what should have been happening the patches actually are not backwards compatible and should have been major releases.

This could be fixed by:
1. reverting `0.4.11` and `0.4.12` and releasing a `0.4.15` without those changes.
1. release changes that were in `0.4.11` and `0.4.12` as `0.5.0`.

Just wanted to post for documentation for others and as feedback. Thanks for your work! Cheers.

**Comment by yury-dymov** [comment]
Hey @hartzis, thank you for the feedback. 

I believe you are right and going forward I will think more about releasing code and versioning more thoughtfully. 
At this time, I feel I would rather keep things as they are to avoid even more confusion
