### ISSUE TITLE
Configure camelize in the meta section

### ISSUE THREAD

**Issue by casertap** [yury-dymov/json-api-normalizer#51]
Hi,
I like to have my data section camelized but some of my meta keys are i18n keys and I would like to keep them uncamelized.
```
meta": {
"aggregations": {
"categories": {
"accessories-opticals": 76,
"accessories-sunglasses": 4,
"jewellery-piercing-top": 1
}
}
}
```
could we have a way to config some section of the meta `aggregations.categories` (or all meta) to stay untouched?

Thanks.

**Comment by yury-dymov** [comment]
Well, I don't think such flexibility justifies configuration complexity, which should be introduced to achieve that. 

If you would like to camelize just part of it, than I recommend to disable camelization for `json-api-normalizer` and apply camelization in your code to parts you need.

**Comment by casertap** [comment]
Hi Yury,
yes you are right, for a config to disable part of the meta section but I am seeing some value in having a config for disabling for the whole meta section though.
Meta can be used for many things that do not really suit the json-api specification initially so having a config to keep it untouched would be nice I think.
What do you think?

**Comment by yury-dymov** [comment]
@casertap based on my experience with other consumers, they want to have meta camelized. I believe that in your case it might be different but I still don't want to introduce another config option for that. Feel free to either fork and implement this in your repo or stick to suggestion above.

**Comment by casertap** [comment]
Actually, I disabled all camelCase and it was not too much of a big deal to camelCase only what was neede d in the js code. 
Thanks
