### ISSUE TITLE
Question about error handling

### ISSUE THREAD

**Issue by iansolano** [yury-dymov/json-api-normalizer#53]
👋 , I have a quick question about error handling.

It seems like this library assumes that a `data` object is always returned in the `json` payload and does not handle the use case where there is a top level `errors` object per JSON API spec https://jsonapi.org/format/#document-top-level. Is this correct (maybe i'm missing something)? If so, is there a way you are currently handling error formatting in the `json` payload?

Thanks in advance!

**Comment by yury-dymov** [comment]
Hey @iansolano, you are correct, library doesn't handle errors. I suppose that if your payload returned error, you wouldn't store the data in regular redux data reducer (and therefore normalize it) but rather dispatch some kind of `error` action instead.

Feel free to share if you have something on your mind.

**Comment by iansolano** [comment]
@yury-dymov Gotcha, thanks for the quick response.

Yeah, if I get a minute in the coming week(s) maybe i'll try and submit a PR. Our issue is that we use `json-api-normalizer` on all our request responses. This only became an issue when trying to have more granular inline error handling on the client.

For example, when an input field validation fails for something like an email we want to return a `200` status but with the errors object. I guess we could parse the response for the errors object and normalize based on its presence or not but it seemed like something nice to have in this library, maybe?

Anyways, thanks for your time!

**Comment by yury-dymov** [comment]
@iansolano currently I don't see any reasons why not to add support for this, so feel free to file a PR and I will be more than happy to review it

**Comment by oyeanuj** [comment]
@iansolano What solution did you end up with here?

**Comment by yury-dymov** [comment]
I think I can safely close this given this thread is more than one year old and generally out of scope of the library functionality
