### ISSUE TITLE
How are data changes handled?

### ISSUE THREAD

**Issue by benlieb** [yury-dymov/json-api-normalizer#56]
Thank you for the library! 

You say this library is great with redux, but I don't really understand how to integrate this with redux. 

If I have a react app, and want to modify this data, so that the app UI changes before I send it to the server, how do I do that? How does this integrate with redux and actions?

Can you give an example?

**Comment by vitorreis** [comment]
+1 here @yury-dymov 

In your article on smash magazine you suggest using it together with [redux-object](https://github.com/yury-dymov/redux-object) for making it easy to work with the data, that makes a lot of sense and seems helpful

Let's say that I want to persist in the redux store a few updates on properties of the object and eventually submit it to a JSON API server, what is the best way of handling this case?

Do you provide a deNormalize method for mapping the redux store to a JSON API PUT/PATCH payload?

Or perhaps the best way is for me to directly update the data in the redux stored (after being normalized) and use [JSONA](https://github.com/olosegres/jsona) to parse it back to a JSON API compliant object?

**Comment by yury-dymov** [comment]
@vitorreis, there are two possible approaches in general:
1. backend driven
2. optimistic ui

Backend driven means that your client never mutate data objects. You just send backend requests, which will return you updates and your client is always in sync. And you never need to "store a few updates and eventually submit to a JSON API sever"

Optimistic UI means that you mutate your data on the client and hope that backend won't fail at the time, when you eventually decided to send updates to the backend. This approach in general is a lot more complex and I can't give any general recommendations as this would hugely vary on case by case basis. 

Per your description, it seems that you have a multiscreen forms or something similar, which requires intermediate state persistence. For such cases I would recommend to have a separate reducer, where I would accumulate all data I need and once ready send everything to the backend without letting client to mutate actual data provided by backend at any point of time.
