### ISSUE TITLE
Could you think about going to 1.x.x? (semver)

### ISSUE THREAD

**Issue by kud** [yury-dymov/json-api-normalizer#59]
It's not totally clear to me but could you think about going to 1.x.x as version because of https://semver.org/#how-do-i-know-when-to-release-100

I use https://github.com/dylang/npm-check and every package under 1.0.0 is considered as non semver packages.

**Comment by yury-dymov** [comment]
I think I can totally do this with the change addressing https://github.com/yury-dymov/json-api-normalizer/issues/9
I am a bit time constrained nowadays but this might happen in a couple weeks

**Comment by kud** [comment]
Great! Thank you :)

**Comment by yury-dymov** [comment]
Yay!
