### ISSUE TITLE
Links are merged if filterEndpoint is set to false

### ISSUE THREAD

**Issue by lvauvillier** [yury-dymov/json-api-normalizer#6]
When `filterEndpoint` is set to false, links are merged.
I don't think this is the expected behavior.

We should have:
```
meta: {
    "/post-block/2620: {
      "?page[cursor]=0": {
        ...
        links: {
          first: "http://example.com/api/v1/post-block/2620?page[cursor]=0",
          next: "http://example.com/api/v1/post-block/2620?page[cursor]=20"            
        }
      },
      "?page[cursor]=20": {
        ...
        links: {
          first: "http://example.com/api/v1/post-block/2620?page[cursor]=0",
          next: "http://example.com/api/v1/post-block/2620?page[cursor]=40"            
        }
      }
    }
  }
```

Instead of:
```
meta: {
    "/post-block/2620: {
      "?page[cursor]=0": {
        ...
      },
      "?page[cursor]=20": {
        ...
      },
      links: {
        first: "http://example.com/api/v1/post-block/2620?page[cursor]=0",
        next: "http://example.com/api/v1/post-block/2620?page[cursor]=40"            
      }
    }
  }
```

**Comment by yury-dymov** [comment]
Hi @lvauvillier,

I thought about but didn't come to the final decision. For pagination current implementation fits better. 

By now I think that it might be better to have both. Save links for each query but also on the higher level preserve the last "links" values.

What do you think?

**Comment by lvauvillier** [comment]
You're right about the fact it's more easy with an endpoint with only pagination params.
But in my case, the app is more complex. I have endpoints with both filtering and pagination params. So, I need to store links for each subqueries and A global link object have no sense as we loose the filtering scope. 

I suggest to store links for each subqueries. With the initial query, it can be simple to write a `build` helper to retrieve the complete loaded dataset resolving each next links. It can be another helper from your `redux-object` library.

**Comment by yury-dymov** [comment]
Ok, let's store links for each subquery and also store the global one for the latest request, at least I don't see any harm from doing that.

If you are OK with that, then feel free to make a PR, or you can wait for a couple of hours and I do this myself.

**Comment by lvauvillier** [comment]
thanks! The change seems easy to do, I just started working on it.
