### ISSUE TITLE
Results as Array instead Object?

### ISSUE THREAD

**Issue by jet112** [yury-dymov/json-api-normalizer#67]
Maybe it will be useful to have an option to get results as array instead object.
Now I get item as object, and each key of item is an item id. But it is inconvenient to iterate them.
Maybe it is possible to create new option, that make items list as array?

**Comment by jet112** [comment]
Also it will be useful if you need to filter, search or map results

**Comment by yury-dymov** [comment]
This would not only be breaking change but also would defeat some of the rationale behind implementing this package. I believe this is the most frequently asked question, which is answered in documentation, article on Smashing Magazine and a lot of closed issue. In short, meta object is available for you, which preserves the order and provides all you need to implement any kind of business logic you need with arrays
