### ISSUE TITLE
Getting a module not found error with core-js

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [yury-dymov/json-api-normalizer#70]
I upgraded to the most recent version and started getting this error.
![Screenshot from 2021-03-19 10-50-52](https://user-images.githubusercontent.com/1622600/111799160-23ffa200-88a1-11eb-9227-85fc87b2418a.png)

**Comment by yury-dymov** [comment]
Thank you, fixed in 1.0.4

**Comment by muyiwaoyeniyi** [comment]
Thank you and thanks for this package.
